### ISSUE TITLE
RGB LEDS

### ISSUE THREAD

**Issue by Bubbles0-0** [zegreatclan/SimHub#330] opened 2019-03-08 06:15 UTC
I am using two strips of 8 LED long RGB run in parallel and they both work and I can change the colours but they are constantly on and not scrolling upwards with the RPM. They do blink when the car maxes out so the LEDS need to be configured correctly but simhub isn't doing this. Any help would be great as this is for a school project and need this done ASAP. 
Thanks in advance, 
Bubbles

**Comment by zegreatclan** [comment] 2019-03-08 06:19
Hi !
You probably mean in series ? Could you attach a screenshot of your LEDs layout settings ? Something should be wrong here. Default settings are intended to work out of box with 16 leds

**Comment by zegreatclan** [comment] 2019-03-08 06:26
For information here is the default mapping , take care of the start and end values, here it is splitted in two separate parts 0 to to 75% and 75% to 100% of map RPM

![image](https://user-images.githubusercontent.com/2207331/54011553-3fdcf300-4173-11e9-81aa-6e2f04f21b18.png)

**Comment by Bubbles0-0** [comment] 2019-03-08 06:33
I mean I have wired the LEDS in parallel so they work at the same time as I am running them next to each other between a gear display. I have set the arduino number to 8 instead of 16 as they are not in a series circuit.
![img_20190308_172319](https://user-images.githubusercontent.com/48345033/54011825-01255800-41c8-11e9-888a-a98ae139f1ac.jpg)
I will give the default a go

**Comment by zegreatclan** [comment] 2019-03-08 06:44
I see, I never tested with LEDs in parallel, not sure if it will work as intended. I can only recommend to go for the official wiring (in series).

For the LEDs configuration in this layout (assuming it works anyway in parallel) you need to edit the LEDs mappings (as shown above) to show on 8leds instead of 16. For instance from LEDs  1 to 5 and 6 to 8. 

If you go in series , all LEDs will be independent so you will just have to duplicate this mapping to show it also on LEDs 9 to 16

**Comment by Bubbles0-0** [comment] 2019-03-08 07:03
I got it working in parallel it was just the mapping of LEDS works like a charm. I just need to change some of the mapping values.
![image](https://user-images.githubusercontent.com/48345033/54013179-519eb480-41cc-11e9-9b93-2b4c1ecdce2b.png)
![img_20190308_180246](https://user-images.githubusercontent.com/48345033/54013237-7c890880-41cc-11e9-80f7-efb3c1a0f8aa.jpg)

**Comment by zegreatclan** [comment] 2019-03-08 07:14
Perfect ! And good luck for your school project !

**Closed by zegreatclan** 2019-03-08 07:14 UTC
Labels: Arduino, question
